FROM node:26.1.0@sha256:c41bbd71d4f71cc65ac836fae7ab69ad1b6ebc3bbfdac94d0ababa7fc1554b39

WORKDIR /app/ui

COPY ui /app/ui

RUN npm install -g corepack@0.34.6 && corepack enable && pnpm install --frozen-lockfile

ENTRYPOINT ["pnpm", "start"]

